name: Deploy to staging
on: 
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploy everything to staging cluster

    steps:
      - name: SSH Into server
      - run : |
          echo ${{secrets.SSH_PRIVATE_KEY}} &> ~/ssh_key
          ssh ssh -i ~/ssh_key ubuntu@13.235.67.14
          cd week-25-next-app/ && git pull
          pnpm i 
          pnpm run build
          pm2 restart all
          